'use client'

import { useEffect, useState, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Header from '@/components/Header'
import type { CaseSetup, VerdictData } from '@/types'

const TONE_LABELS: Record<string, string> = {
  serious: '🏛️ Serious Courtroom',
  warm: '🤗 Warm & Caring',
  fun: '😂 Fun & Silly',
  sarcastic: '🙄 Sarcastic',
  dramatic: '🎭 Dramatic',
}

const LANGUAGE_LABELS: Record<string, string> = {
  english: '🇺🇸 English',
  mandarin: '🇨🇳 中文 (Mandarin)',
  bilingual: '🌏 English + 中文',
}

const SCORE_COLORS = [
  { bg: 'bg-gold-500', text: 'text-gold-400' },
  { bg: 'bg-blue-500', text: 'text-blue-400' },
  { bg: 'bg-emerald-500', text: 'text-emerald-400' },
  { bg: 'bg-purple-500', text: 'text-purple-400' },
]

// ── Helpers ──────────────────────────────────────────────────────────────────

function AnimatedBar({ score, colorClass, delay = 0 }: { score: number; colorClass: string; delay?: number }) {
  const [width, setWidth] = useState(0)
  useEffect(() => {
    const t = setTimeout(() => setWidth(score), delay + 100)
    return () => clearTimeout(t)
  }, [score, delay])
  return (
    <div className="w-full bg-navy-800 rounded-full h-4 overflow-hidden print-score-track">
      <div className={`h-full rounded-full transition-all duration-1000 ease-out ${colorClass}`} style={{ width: `${width}%` }} />
    </div>
  )
}

function buildVerdictText(verdict: VerdictData, setup: CaseSetup, date: string): string {
  const LINE = '─'.repeat(44)
  const scores = Object.entries(verdict.scores)
  const maxScore = Math.max(...scores.map(([, s]) => s))

  const scoreLines = scores
    .map(([name, score]) => {
      const filled = Math.round(score / 10)
      const bar = '█'.repeat(filled) + '░'.repeat(10 - filled)
      return `  ${name.padEnd(14)} ${bar}  ${score}/100${score === maxScore ? '  ★ Winner' : ''}`
    })
    .join('\n')

  const argLines = setup.parties
    .map(p => `  ${p}:\n  ${verdict.keyArguments[p] || 'No argument recorded.'}`)
    .join('\n\n')

  return [
    '⚖️  AI JUDGE VERDICT',
    LINE,
    '',
    `Case:         ${verdict.caseTitle}`,
    `Parties:      ${setup.parties.join(' vs. ')}`,
    `Relationship: ${setup.relationship}`,
    `Date:         ${date}`,
    '',
    LINE,
    'A. KEY ARGUMENTS',
    LINE,
    argLines,
    '',
    LINE,
    'B. THE RIGHTNESS METER',
    LINE,
    scoreLines,
    '',
    LINE,
    'C. REASONING',
    LINE,
    verdict.reasoning,
    '',
    LINE,
    'D. RESOLUTION & RELATIONSHIP REPAIR',
    LINE,
    verdict.resolution,
    '',
    LINE,
    'Generated by AI Judge',
  ].join('\n')
}

// ── Share button sub-component ────────────────────────────────────────────────

function ShareBtn({
  onClick,
  icon,
  label,
  active,
  activeLabel,
}: {
  onClick: () => void
  icon: React.ReactNode
  label: string
  active?: boolean
  activeLabel?: string
}) {
  return (
    <button
      onClick={onClick}
      className={`flex flex-col items-center justify-center gap-2 px-3 py-4 rounded-xl border
        transition-all duration-200 text-center active:scale-95 select-none
        ${active
          ? 'bg-emerald-500/15 border-emerald-500/50 text-emerald-300'
          : 'bg-navy-800/60 border-navy-700 text-navy-200 hover:bg-navy-700/80 hover:border-navy-500 hover:text-white'
        }`}
    >
      <span className="text-xl leading-none">{icon}</span>
      <span className="text-xs font-semibold tracking-wide">
        {active && activeLabel ? activeLabel : label}
      </span>
    </button>
  )
}

// ── Icons (inline SVG, no deps) ───────────────────────────────────────────────

const IconCopy = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
    <rect x="9" y="9" width="13" height="13" rx="2" />
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
  </svg>
)
const IconPrint = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
    <polyline points="6 9 6 2 18 2 18 9" />
    <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
    <rect x="6" y="14" width="12" height="8" />
  </svg>
)
const IconEmail = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
    <polyline points="22,6 12,13 2,6" />
  </svg>
)
const IconShare = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
    <circle cx="18" cy="5" r="3" />
    <circle cx="6" cy="12" r="3" />
    <circle cx="18" cy="19" r="3" />
    <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
    <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
  </svg>
)

// ── Main verdict page ─────────────────────────────────────────────────────────

function VerdictContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [verdict, setVerdict] = useState<VerdictData | null>(null)
  const [setup, setSetup] = useState<CaseSetup | null>(null)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)
  const [hasNativeShare, setHasNativeShare] = useState(false)

  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  useEffect(() => {
    try {
      const verdictParam = searchParams.get('verdict')
      const setupParam = searchParams.get('setup')
      if (!verdictParam || !setupParam) throw new Error('Missing data')
      setVerdict(JSON.parse(decodeURIComponent(verdictParam)))
      setSetup(JSON.parse(decodeURIComponent(setupParam)))
    } catch {
      setError('Could not load verdict. Please try again.')
    }
  }, [searchParams])

  useEffect(() => {
    setHasNativeShare(typeof navigator !== 'undefined' && !!navigator.share)
  }, [])

  const handleCopy = async () => {
    if (!verdict || !setup) return
    try {
      await navigator.clipboard.writeText(buildVerdictText(verdict, setup, date))
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback: select a hidden textarea
    }
  }

  const handlePrint = () => window.print()

  const handleEmail = () => {
    if (!verdict || !setup) return
    const subject = `AI Judge Verdict: ${setup.parties.join(' vs. ')}`
    const body = buildVerdictText(verdict, setup, date)
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  }

  const handleNativeShare = async () => {
    if (!verdict || !setup) return
    const text = buildVerdictText(verdict, setup, date)
    try {
      await navigator.share({
        title: `AI Judge Verdict: ${setup.parties.join(' vs. ')}`,
        text,
      })
    } catch {
      // User cancelled or share failed — no action needed
    }
  }

  if (error) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1 flex flex-col items-center justify-center gap-4 px-4">
          <p className="text-red-400">{error}</p>
          <button onClick={() => router.push('/')} className="btn-secondary">Start Over</button>
        </div>
      </div>
    )
  }

  if (!verdict || !setup) {
    return (
      <div className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-navy-400 animate-pulse">Loading verdict...</div>
        </div>
      </div>
    )
  }

  const partyEntries = Object.entries(verdict.scores)
  const maxScore = Math.max(...partyEntries.map(([, s]) => s))

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header hidden on print via CSS */}
      <Header />

      <main id="verdict-print-area" className="max-w-2xl mx-auto w-full px-4 py-8 space-y-6">

        {/* Print-only title (hidden on screen) */}
        <div className="hidden print:block text-center pb-2 border-b border-gray-300 mb-2">
          <p className="text-2xl font-bold text-gray-900">⚖️ AI Judge Verdict</p>
          <p className="text-sm text-gray-500">{date}</p>
        </div>

        {/* Case Summary */}
        <div className="verdict-card" style={{ animationDelay: '0ms' }}>
          <div className="section-label">🎙️ Case Summary</div>
          <h2 className="text-2xl font-bold text-white leading-tight mb-3 print:text-gray-900">
            {verdict.caseTitle}
          </h2>
          <div className="flex flex-wrap gap-x-4 gap-y-1 text-sm">
            <span className="text-navy-300 print:text-gray-600">
              <span className="text-navy-500 print:text-gray-400">Parties: </span>
              {setup.parties.join(', ')}
            </span>
            <span className="text-navy-300 print:text-gray-600">
              <span className="text-navy-500 print:text-gray-400">Relationship: </span>
              {setup.relationship}
            </span>
            <span className="text-navy-300 print:text-gray-600">
              <span className="text-navy-500 print:text-gray-400">Verdict Tone: </span>
              {TONE_LABELS[setup.tone]}
            </span>
            {setup.language && setup.language !== 'english' && (
              <span className="text-navy-300 print:text-gray-600">
                <span className="text-navy-500 print:text-gray-400">Language: </span>
                {LANGUAGE_LABELS[setup.language]}
              </span>
            )}
            <span className="text-navy-300 print:text-gray-600">
              <span className="text-navy-500 print:text-gray-400">Date: </span>
              {date}
            </span>
          </div>
        </div>

        {/* A. Key Arguments */}
        <div className="verdict-card" style={{ animationDelay: '100ms' }}>
          <div className="section-label">A. Key Arguments</div>
          <div className="space-y-4">
            {setup.parties.map((party, i) => {
              const arg = verdict.keyArguments[party] || 'No argument recorded.'
              const color = SCORE_COLORS[i % SCORE_COLORS.length]
              return (
                <div key={party} className="flex gap-3">
                  <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold
                    bg-navy-800 border-2 ${color.text} border-current print:bg-gray-100 print:border-gray-400 print:text-gray-700`}>
                    {party[0]?.toUpperCase()}
                  </div>
                  <div className="flex-1">
                    <p className={`font-bold text-sm mb-1 ${color.text} print:text-gray-900`}>{party}</p>
                    <p className="text-navy-200 text-sm leading-relaxed print:text-gray-700">{arg}</p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* B. The Rightness Meter */}
        <div className="verdict-card" style={{ animationDelay: '200ms' }}>
          <div className="section-label">B. The Rightness Meter</div>
          <div className="space-y-5">
            {partyEntries.map(([party, score], i) => {
              const color = SCORE_COLORS[i % SCORE_COLORS.length]
              const isWinner = score === maxScore
              return (
                <div key={party} className="space-y-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className={`font-bold text-base ${color.text} print:text-gray-900`}>{party}</span>
                      {isWinner && (
                        <span className="text-xs bg-gold-500/20 text-gold-300 px-2 py-0.5 rounded-full border border-gold-500/30 font-medium print:bg-yellow-50 print:text-yellow-700 print:border-yellow-300">
                          Winner
                        </span>
                      )}
                    </div>
                    <span className={`text-2xl font-black ${color.text} print:text-gray-900`}>
                      {score}<span className="text-sm font-normal text-navy-400 print:text-gray-500">/100</span>
                    </span>
                  </div>
                  <AnimatedBar score={score} colorClass={color.bg} delay={i * 150} />
                </div>
              )
            })}
          </div>
        </div>

        {/* C. Reasoning */}
        <div className="verdict-card" style={{ animationDelay: '300ms' }}>
          <div className="section-label">C. Reasoning</div>
          <p className="text-navy-200 leading-relaxed whitespace-pre-line print:text-gray-700">{verdict.reasoning}</p>
        </div>

        {/* D. Resolution & Relationship Repair */}
        <div className="verdict-card border-gold-600/40" style={{ animationDelay: '400ms' }}>
          <div className="section-label">D. Resolution & Relationship Repair</div>
          <p className="text-navy-200 leading-relaxed whitespace-pre-line print:text-gray-700">{verdict.resolution}</p>
        </div>

        {/* ── Share & Export ─────────────────────────────────────── */}
        <div className="print:hidden space-y-4">
          {/* Divider */}
          <div className="flex items-center gap-3">
            <div className="flex-1 h-px bg-navy-800" />
            <span className="text-navy-500 text-[11px] uppercase tracking-widest font-semibold">Share & Export</span>
            <div className="flex-1 h-px bg-navy-800" />
          </div>

          {/* Buttons */}
          <div className={`grid gap-3 ${hasNativeShare ? 'grid-cols-2 sm:grid-cols-4' : 'grid-cols-3'}`}>
            <ShareBtn
              onClick={handleCopy}
              icon={copied
                ? <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} className="w-5 h-5"><polyline points="20 6 9 17 4 12" /></svg>
                : IconCopy}
              label="Copy Text"
              active={copied}
              activeLabel="Copied!"
            />
            <ShareBtn
              onClick={handlePrint}
              icon={IconPrint}
              label="Save PDF"
            />
            <ShareBtn
              onClick={handleEmail}
              icon={IconEmail}
              label="Email"
            />
            {hasNativeShare && (
              <ShareBtn
                onClick={handleNativeShare}
                icon={IconShare}
                label="Share"
              />
            )}
          </div>

          <p className="text-center text-navy-600 text-xs">
            Copy → paste into WeChat, iMessage, or anywhere else
          </p>
        </div>

        {/* ── Gavel + Judge Another Case ─────────────────────────── */}
        <div className="print:hidden">
          <div className="flex items-center gap-4 py-2 mb-6">
            <div className="flex-1 h-px bg-navy-800" />
            <span className="text-2xl">🔨</span>
            <div className="flex-1 h-px bg-navy-800" />
          </div>
          <button
            onClick={() => router.push('/')}
            className="btn-primary w-full flex items-center justify-center gap-2 text-lg py-4"
          >
            ⚖️ Judge Another Case
          </button>
        </div>

        {/* Print-only footer */}
        <div className="hidden print:block text-center pt-4 border-t border-gray-300 text-xs text-gray-400">
          Generated by AI Judge
        </div>

      </main>
    </div>
  )
}

export default function VerdictPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center text-navy-400">Loading verdict...</div>}>
      <VerdictContent />
    </Suspense>
  )
}
